"""fix timezone aware datetimes

Revision ID: 17e29d8097a0
Revises: c53b60d0d9bd
Create Date: 2026-06-17 19:49:45.223825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '17e29d8097a0'
down_revision: Union[str, Sequence[str], None] = 'c53b60d0d9bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('zone', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('zone', 'is_active')
    op.drop_column('event', 'is_active')
    # ### end Alembic commands ###
